include "application.conf"

slick.dbs.default.db.url      = "jdbc:postgresql://localhost:5432/doto"
slick.dbs.default.db.user     = "shivakomatreddy"
slick.dbs.default.db.password = ""

jwt.secret = "dev-jwt-secret-do-not-use-in-production-min-32-chars"

play.http.secret.key = "dev-app-secret-do-not-use-in-production-min-32-chars"
