include "application.conf"

slick.dbs.default.db.url      = ${?DOTO_TEST_DB_URL}
slick.dbs.default.db.user     = ${?DOTO_TEST_DB_USER}
slick.dbs.default.db.password = ${?DOTO_TEST_DB_PASSWORD}

slick.dbs.default.db.url      = "jdbc:postgresql://localhost:5432/doto_test"
slick.dbs.default.db.user     = "shivakomatreddy"
slick.dbs.default.db.password = ""

play.http.secret.key = "test-secret-key-do-not-use-in-production"
jwt.secret           = "test-jwt-secret-do-not-use-in-production-min-32"
